### ISSUE TITLE
Create a wiki page describing portal and Zeppelin interaction

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#143]

**Comment by stvoutsin** [comment]
Some more info after a discussion on Slack 

We are planning on having a portal website, and the Zeppelin website itself.
At some point we are going to need to pass some kind of authentication tokens between them, so that a user logged in to the portal can use zeppelin.
For this task we are looking for Ideas for how the portal and Zeppelin can pass information between them
Is there any established best practice for this, etc..

**Comment by Zarquan** [comment]
Do we have a page for this ?

**Comment by stvoutsin** [comment]
Is this task still ongoing? Does this page cover what we want: https://github.com/wfau/aglais/wiki/Zeppelin:-Documentation-of-Portal---Zeppelin-Interaction ?

**Comment by Zarquan** [comment]
Yep - done
