### ISSUE TITLE
List of WFAU archives to include

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#180]

**Comment by NigelHambly** [comment]
My suggestion is that we limit ourselves to the major all-sky (or most-of-sky) photometric catalogues that are extensively used in conjunction with the Gaia data. The idea is to get as much wavelength coverage from optical, through NIR, to IR. Hence my suggested set is: PanSTARRS DR1 (3/4 sky; grizy 0.5um to 1.1um); 2MASS (JHKs; 1.2um to 2.4um) and ALLWISE (W1,2,3,4; 3.4um to 22um). We have the latter two already at WFAU; my understanding is that we're in the process of getting the first. More details (detailed schemata, row counts, csv data volume etc.) to follow in further comments.

**Comment by NigelHambly** [comment]
Details: 

PanSTARRs PS1 DR1 (suggest not DR2 - may not be available in time, and is more geared towards multi-epoch products IIUC): mean attributes column subset available from WFAU (i.e. already transferred across the pond): 1.92 billion rows, 1TB csv.

ALLWISE: full monty (?, i.e. not column subset): 0.75 billion rows, 1.3 TB csv for all columns, could retransfer from NASA/IPAC IRSA or outgest from WFAU MS SQL (at the same time creating a column selection).

2MASS: recommend Point Source Catalogue only (i.e. no extended objects nor extended mission ancillary products): 0.47 billion rows, 0.3 TB (uncompressed, | separated ascii not csv) or a column subset outgest from WFAU MS SQL if preferred.

**Comment by NigelHambly** [comment]
AXS aspects: if we're going to piggy-back on AXS (which I think we should to provide some level of spatial organisation, ease of crossmatch-on-the-fly and a few nice API extensions specific to astronomy applications) then see

https://astronomy-commons.github.io/axs/importing_data.html#importing-new-data-from-scratch

i.e. we likely want to load initially from ascii/csv via a python script defining dtypes etc as was done for Gaia DR2 in the prototype. Then we can use AXS distributed transformation (save_axs_table) to create/register/persist the bucketed, zoned and distributed version of the table amenable to access via axs if required. So we still need to define the table schemas in order to create a spark data frame in order to use this axs import mechanism. My suggestion is that I define annotated MS SQL schemas for PS1 DR1 and Gaia EDR3 (we already have them for 2MASS and ALLWISE, full column sets) then we can perhaps generate the python data structure definitions from those (even automatically via some code if we're feeling brave). 

Only downside with all this is the large amount of disk storage we'll need for multiple copies (3 IIUC) persisted on disk simultaneously: raw csv, non-axs parquet and then axs-parquet. Rough estimate is around 10 TB.

**Comment by NigelHambly** [comment]
SQL schema for GEDR3 is now available in the WFAU SVN at https://forge.roe.ac.uk/svn/VDFSarchive/trunk

(2MASS and WISE already there; just need to put in a PS1 DR1 version based on Mike Read's column subset).

**Comment by Zarquan** [comment]
Pull request #202 adds a CephFS mount of the Gaia DR2 dataset and 1Tbyte user space to the Ansible deployment.

**Comment by Zarquan** [comment]
Issue #187 is looking at the directory structure for the data sets.

**Comment by NigelHambly** [comment]
PS1 schema available at https://gaia.esac.esa.int/dpacsvn/DPAC_branches/CU5/software/personal/nhambly/ReformattingTools/data/create_tables.sql.txt

#42 shows how to create the necessary pyspark structures from sql schemas while #164 details how to get the data in. This issue is now closed.
