### ISSUE TITLE
Create folders for curated examples

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#234]

**Comment by NigelHambly** [comment]
I'll take this. I'm a bit unfamiliar with Git, so will need some hand-holding.

Seems to me we should use the wfau/aglais git project as a repo for our notebooks/examples. Hence we should establish a folder tree from that project root in git, right? I'm uncertain how a given Zeppelin session then connects to this repo but ultimately it would be good to have a single location for the curated example notebooks rather than several copies lurking around in Zeppelin, Git, and the DPAC SVN (which I'm most familiar with, and trust, and am using as a fall-back / back-up as I don't understand the other things enough to trust them yet).

**Comment by Zarquan** [comment]
@NigelHambly, @stvoutsin 
Hi  Nigel, Stelios has created the [aglais-notebooks](https://github.com/wfau/aglais-notebooks) project in GitHub as a place to maintain and curate the notebook examples we want to offer to our public users. The idea was to keep the two parts of the project separate, the technical details of the platform and how it is deployed here in the main _aglais_ project and aim the _aglais-notebooks_ project at the right level of detail for our data-science users.
At the moment we have been adding issues about the curated notebooks here because the _aglais-notebooks_ project is still getting started. Once _aglais-notebooks_ project is under way we can move to adding issues there, and invite external users to contribute to them as well.

First task in the _aglais-notebooks_ project will probably be to give the notebooks sensible names rather than just the raw generated names like `2A94M5J1Z` that Zeppelin gave them when they were created.

**Comment by NigelHambly** [comment]
Given what was discussed yesterday is this issue still relevant, or are we moving away from use of gh for this purpose?

**Comment by Zarquan** [comment]
This is the main repository until/if we decide if we want to move them somewhere else.

**Comment by Zarquan** [comment]
The main thing I wanted to raise yesterday was just to ask _"Given we can't edit really view or edit them in GitHub, is this the best place for them ?"_

**Comment by NigelHambly** [comment]
For the time being I'm committing reasonably polished versions of example scripts to git via the live system in folder AglaisPublicExamples. As a belt-and-braces back-up these are also going into the DPAC SVN at

https://gaia.esac.esa.int/dpacsvn/DPAC_branches/CU9/docs/personal/nhambly/ZeppelinNotebooks/AglaisPublicExamples/

**Comment by Zarquan** [comment]
The git commit worked and there is a new version stored in the GitHub repository.

**Comment by NigelHambly** [comment]
In a personal fork of [aglais-notebooks](https://github.com/NigelHambly/aglais-notebooks) I have decided on the simplified folder structure that will be presented to the users on the Zeppelin home page. Further work in this regard will now be logged under #443 and I'm closing this as done.
