### ISSUE TITLE
Export notebook to file

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#36]
Basic export notebook function to export and download a notebook as a text file.

**Comment by NigelHambly** [comment]
In jupyter I can save in a variety of formats, including ipynb for importing back, pdf for inclusion in other docs (and raw python plain text script). I would like to see at least the first of these options, not least so that I can preserve my Zeppelin scripts outside of the cloud and easily put them back in if the latter evaporates unexpectedly...

**Comment by stvoutsin** [comment]
Unfortunately it looks like Zeppelin only allows you to export the notebook as a JSON file, definitely a drawback compared to Jupyterhub. Do we want to close this issue, or leave it open in case there is a new version or external library that supports other formats?

**Comment by NigelHambly** [comment]
The letter of the issue is "export notebook to file" which is covered by the standard .json download facility. The spirit is a set of bigger issues: ideally we want export in a variety of formats, some human readable. Furthermore how do we import a .json back in?! Maybe that last one is covered by other tickets. But it strikes me as fundamental to the "code-to-data" mantra...!

If we're operating on the literal letter of the issue, then I suppose it can be closed. Maybe the other things mentioned above are outwith the scope anyway.

**Comment by Zarquan** [comment]
Technically, this issue is closed, but based on the comments above we open up a whole set of new ones.
* Instructions on how to import JSON file generated by 'export as file' #50 
* Export a notebook as a PDF (basic formatting) #51
* Export a notebook as an executable Python program #52

**Comment by Zarquan** [comment]
Any more new issues we should create before we close this one ?

**Comment by NigelHambly** [comment]
None directly related to this.

**Comment by Zarquan** [comment]
Ok, closing this one ...
