### ISSUE TITLE
Automatically run pyspark code at the start of a SparkContext

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#486]
Automatically run some pyspark code at the start of a SparkContext.
This is to automate the database configuration steps that are added by manually running the SetUp notebook.

**Comment by NigelHambly** [comment]
In anticipation of this I've moved the Set Up notebook out of the public examples folder and in to my own private folder under users.

**Comment by NigelHambly** [comment]
I have one doubt: what happens if a user resets the spark context via the "circular arrows" icon in the interpreter bindings cog in the zeppelin UI? Will the automatic initialisation run again?

Also note that I'll be adding a lot more into this for DR3: all schema structures for new tables, DR3 default DB set-up and definitions for data resources against the parquet file sets (which I will take care of). If you can point me to where in the repo code base the automatically executed script will reside, I can then make sure I update it with the new parts of the set-up when I'm ready.

**Comment by Zarquan** [comment]
I think the current idea was to have an import statement at the top of all our notebooks that imported and ran some Python code that we have installed in a library that is automatically loaded alongside matplotlib, numpy etc.

The import statement would load a Python class that would automatically run the initialisation code in that class.
The initialisation code would check to see if the Gaia schema was already defined, and if not, it would run the appropriate steps to define it.
The code would be designed to be idempotent, so it doesn't matter how many time it gets run, it only (re)defines the schemas if they are not there.

**Comment by NigelHambly** [comment]
Ah yes thanks for reminding me. If you can set up in the code base a skeleton python library/module file based on the existing setup notebook (which note is now under my nch users folder) and point me to it, I will populate it with all the necessary additional DR3 stuff.

**Comment by stvoutsin** [comment]
Fixed in:
https://github.com/wfau/aglais/pull/677
and:
https://github.com/wfau/gaiadmpsetup
