### ISSUE TITLE
Version control for gaiaxpy

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#629]
How do we handle different versions of the gaiaxpy library ?

If upstream release a new version of gaiaxpy that has different dependencies, we would want to evaluate it on a test or dev system before we update the live system.

What do we need to put in place to manage that ?

**Comment by stvoutsin** [comment]
Quick update on GaiaXPy:

I've had a go installing GaiaXPy with the newer versions of the packages that we install in our current system, and while the installation completes without an error, when running the pytests that GaiaXPy comes with, we get one fail.
The failed test seems to be related to the pandas library, as I tried downgrading pandas, and the tests all pass.

Several different options for moving this forward:

a) Downgrade pandas package only. (Requires testing all of our notebooks to make sure nothing is broken) I can start a test now just to give us some better info.
b) Keep current (newer) version of the required packages, and include the installation of GaiaXPy in our next deployment, and start using it regardless of test error. Raise a ticket in Gaia's Jira
c) Don't include GaiaXPy at all for now. Raise a ticket in Gaia's Jira
d) Other?

Notes on tests can be found here: https://github.com/stvoutsin/aglais/blob/c6a4787741a0fb9b72e2e69cde81f450f1390f08/notes/stv/20220203-gaiaxpy-pytests.txt

**Comment by Zarquan** [comment]
Two separate issues - install GaiaXPy on our current system #627, and a longer term issue about version control (this one).

**Comment by NigelHambly** [comment]
Which version of GaiaXPy are we talking about? There is currently no formal release and it's evolving under our feet, but latest communication (Dec 2021) to DPAC from the Cambridge development team concerns a version 0.0.6 which has a few new features, but perhaps more importantly "some bug fixes". I don't suppose those fixes will affect the dependency issue, but if we're not at 0.0.6 it might be worth checking out the latest version. There's no branch or tagging of this product yet in the DPAC SVN, but I note that there's a version badge under folder gaiaxpy, __init.py__.__version__ which is labelled "0.0.6.patch".

Regarding the different options a) to d) above, I think I favour b) even if no problems are identified by downgrading (option a). My thinking is that it'll be easier to diagnose and fix at such time as a runtime problem crops up when somebody is using GaiaXPy, as opposed to something weird that happens to anybody using the system generally (and not using GaiaXPy) because of a runtime conflict imposed by downgrading Pandas.

**Comment by stvoutsin** [comment]
The version that we have cloned is 0.0.6.patch
After a discussion in todays telecon we are going with option b, i.e install gaiaxpy, but keep the package versions that we currently use

**Comment by Zarquan** [comment]
I think option (b) been done ?

**Comment by NigelHambly** [comment]
Superseded by #825
