### ISSUE TITLE
Missing clear cache in Random Forrest classifier example

### ISSUE THREAD

**Issue by Zarquan** [wfau/aglais#671]
The _"Random Forrest classifier"_ example contains an explicit cache command, but it doesn't have the corresponding clear cache at the end. Is this a problem ?
```
raw_sources_cached = raw_sources_df.cache()
....
....
```

**Comment by Zarquan** [comment]
Note - this depends on whether or not we want to include cache commands in our examples (see #670).

**Comment by NigelHambly** [comment]
Tricky one. If the notebook is run from end-to-end in one go then there's probably no need to have an explicit cache: it will execute with optimum performance given the current system set up and configuration. But if somebody runs it cell by cell, pausing half way down to go off and make a cup of tea, then IIUC expensive upstream cells may well re-run because earlier stages of the workflow need repeating (because in-memory objects have been cleared after time-out?). 

On balance I guess we shouldn't encourage users to cache as it's a bit selfish and irresponsible in an egalitarian multi-user scenario. I'll test out performance with and without to try to inform my decision, but atm I'm leaning towards expunging any mention of caching in our notebooks...

**Comment by NigelHambly** [comment]
Run 1: notebook run end-to-end with explicit cache:
- start time 12:02:35
- end time 12:12:00

wall-clock run time is 11m25s.

**Comment by NigelHambly** [comment]
Run 2: end-to-end with caching removed:
- start time 12:22:56
- end time 13:06:37
wall-clock run time is 43m41s

**Comment by NigelHambly** [comment]
Run 3: same as run 1 as a repeatability check:

- start time 13:21:23
- end time 13:30:32

wall-clock run time is 9m09s

**Comment by Zarquan** [comment]
We need to check what the implications of caching are for multiple users.
If one user holds on to data in the cache, it may hold on to resources and prevent others from executing their jobs.

**Comment by NigelHambly** [comment]
Clearly there will be implications for other users if one user hogs resources. My feeling is that it's better that a single user gets what they want out of a responsive system, and gets out of the way quickly for the next user, rather than the available resources being spread so thinly that nobody can do anything useful with a hopelessly sluggish system that is constantly having to re-execute the IO-heavy parts of workflows (especially given our current IO-bound performance). It seems to me this is more in tune with the Spark cluster philosophy of doing one job at a time.

For the time being I suggest we point out to users the usefulness of caching, with appropriate caveats/warnings about using such things responsibly (and I'll ensure appropriate cache clearing tidy-up cells are put at the end of the relevant notebooks). As long as users execute a clear cache and log out when they're finished that'll cover it, no?

**Comment by NigelHambly** [comment]
Clear cache added at the end of the notebook.

**Comment by Zarquan** [comment]
Closing this issue which was specific to the RandomForestClassifier notebook, which has been fixed.
